# УДАЛЕНО: импорт PriceChanelGridSignals


def plot_data():
    return {
        "legend": "PriceChanelGrid",
        "required_columns": [
            "OPEN",
            "CLOSE",
            "HIGH",
            "LOW",
            "DATE",
            "PC_20_HIGH",
            "PC_20_LOW",
            "PC_20_MID",
            "ST_UPPER_30_7",
            "ST_LOWER_30_7",
            "BUY_PRICE",
            "SELL_PRICE",
            "SL_PRICE",
            "CT_PRICE",
            "CE_PRICE",
        ],
        "plots": [
            {"column": "PC_20_HIGH", "color": "#7B93FF", "width": 2},
            {"column": "PC_20_LOW", "color": "#7B93FF", "width": 2},
            {"column": "PC_20_MID", "color": "#BFFF2B", "width": 3},
            {"column": "ST_UPPER_30_7", "color": "#FA0000", "width": 3},
            {"column": "ST_LOWER_30_7", "color": "#006400", "width": 3},
        ],
        "actions": [
            {"column": "BUY_PRICE", "color": "#000000", "style": "x", "width": 2},
            {"column": "SELL_PRICE", "color": "#000000", "style": "x", "width": 2},
            {"column": "SL_PRICE", "color": "#000000", "style": "x", "width": 2},
            {"column": "CT_PRICE", "color": "#000000", "style": "x", "width": 2},
            {"column": "CE_PRICE", "color": "#000000", "style": "x", "width": 2},
        ],
        "signals": [
            {
                "name": "BUY",
                "price_col": "BUY_PRICE",
                "offset": -1,
                "color": "#4a6",
                "style": "^",
                "legend": "buy",
                "width": 2,
            },
            {
                "name": "SELL",
                "price_col": "SELL_PRICE",
                "offset": 1,
                "color": "#4a6",
                "style": "o",
                "legend": "sell",
                "width": 2,
            },
            {
                "name": "STOP_LOSS",
                "price_col": "SL_PRICE",
                "offset": 1,
                "color": "#FF5B5B",
                "style": "p",
                "legend": "stop loss",
                "width": 2,
            },
            {
                "name": "CLOSE_TIME",
                "price_col": "CT_PRICE",
                "offset": 1,
                "color": "#3C74BD",
                "style": "d",
                "legend": "close time",
                "width": 2,
            },
            {
                "name": "CLOSE_END",
                "price_col": "CE_PRICE",
                "offset": 1,
                "color": "#000000",
                "style": "*",
                "legend": "close end",
                "width": 2,
            },
        ],
    }
