def plot_data():
    return {
        "legend": "PriceChanelGrid",
        "required_columns": [
            "OPEN",
            "CLOSE",
            "HIGH",
            "LOW",
            "DATE",
            "PC 20 HIGH",
            "PC 20 LOW",
            "PC 20 MID",
            # "SIGNAL",
            # "TAKE_PROFIT",
            # "STOP_LOSS",
            # "BUY_PRICE",
            # "SELL_PRICE",
        ],
        "plots": [
            {"column": "PC 20 HIGH", "color": "#7B93FF", "width": 2},
            {"column": "PC 20 LOW", "color": "#7B93FF", "width": 2},
            {"column": "PC 20 MID", "color": "#BFFF2B", "width": 3},
            # {"column": "ST 20 5 LOW", "color": "#006400", "width": 3},
            # {"column": "EMA 50", "color": "#3C74BD", "width": 1},
            # {"column": "TAKE_PROFIT", "color": "#47F77B", "width": 1},
            # {"column": "STOP_LOSS", "color": "#FF5B5B", "width": 1},
        ],
        "actions": [
            # {"column": "BUY_PRICE", "color": "#000000", "style": "x", "width": 2},
            # {"column": "SELL_PRICE", "color": "#000000", "style": "x", "width": 2},
        ],
        "signals": [
            # {
            #     "name": DoubleTrendSignals.LONG_BUY,
            #     "price_col": "BUY_PRICE",
            #     "offset": -1,
            #     "color": "#4a6",
            #     "style": "^",
            #     "legend": "buy",
            #     "width": 2,
            # },
            # {
            #     "name": DoubleTrendSignals.LONG_SELL,
            #     "price_col": "SELL_PRICE",
            #     "offset": 1,
            #     "color": "#4a6",
            #     "style": "o",
            #     "legend": "sell",
            #     "width": 2,
            # },
            # {
            #     "name": DoubleTrendSignals.LONG_TP,
            #     "price_col": "TAKE_PROFIT",
            #     "offset": 1,
            #     "color": "#4a6",
            #     "style": "p",
            #     "legend": "take profit",
            #     "width": 2,
            # },
            # {
            #     "name": DoubleTrendSignals.LONG_SL,
            #     "price_col": "STOP_LOSS",
            #     "offset": -1,
            #     "color": "#4a6",
            #     "style": "p",
            #     "legend": "stop loss",
            #     "width": 2,
            # },
        ],
    }
